Feature/Localdev-update: Implement NtvSectionAdapter on GridView, ListView
NativoPlatform/NativoSDK-Android-UnifiedSample pull request #35
Opened 2022-06-16 12:57 UTC by K-thao

- Converted some classes to **Kotlin**
- Implement `NtvSectionAdapter` on `GridViewAdapter`, `ListViewAdapter`
- Use common constant variable for **tag**.

2022-06-16 18:03 UTC, MattMur requested changes
Needs a bit of work but looking good

2022-06-16 18:03 UTC, MattMur commented on app/src/main/java/com/nativo/sampleapp/ViewAdapter/ListViewAdapter.kt
> +        Log.d(NtvTAG, "didAssignAdToLocation: $location")
When an ad gets assigned to a location, you should add an extra row to your datasource(integerList) and then inject that row here

2022-06-16 18:03 UTC, MattMur commented on app/src/main/java/com/nativo/sampleapp/ViewAdapter/GridViewAdapter.kt
> +        Log.d(NtvTAG, "didAssignAdToLocation: $location")
When an ad gets assigned to a location, you should add an extra row to your datasource(integerList) and then inject that row here

2022-06-16 18:20 UTC, K-thao commented on app/src/main/java/com/nativo/sampleapp/ViewAdapter/GridViewAdapter.kt
> +        initSectionWithAdapter(this, SECTION_URL, context)
Fixed.

2022-06-16 18:20 UTC, K-thao commented on app/src/main/java/com/nativo/sampleapp/ViewAdapter/GridViewAdapter.kt
> +import net.nativo.sdk.NativoSDK.placeAdInView
Fixed.

2022-06-16 18:20 UTC, K-thao commented on app/src/main/java/com/nativo/sampleapp/ViewAdapter/GridViewAdapter.kt
> +    inner class ItemViewHolder(private val container: View) {
Fixed.

2022-06-16 18:20 UTC, K-thao commented on app/src/main/java/com/nativo/sampleapp/ViewAdapter/GridViewAdapter.kt
> +                    placeAdInView(container, gridView, SECTION_URL, position, null)
Fixed.

2022-06-16 18:21 UTC, K-thao commented on app/src/main/java/com/nativo/sampleapp/ViewAdapter/ListViewAdapter.kt
> +    private fun bindView(container: View, item: Int, i: Int) {
Fixed.

2022-06-16 20:15 UTC, MattMur requested changes

2022-06-16 20:15 UTC, MattMur commented on app/src/main/java/com/nativo/sampleapp/ViewAdapter/GridViewAdapter.kt
> +
What is this for? I don't see this used anywhere.

2022-06-16 20:15 UTC, MattMur commented on app/src/main/java/com/nativo/sampleapp/ViewAdapter/GridViewAdapter.kt
>              if (shouldShowPlaceAd(item)) {
What I would recommend is have an 'else' condition after this, so if 'shouldShowPlaceAd()' is false, then you add a click listener.

2022-06-17 18:07 UTC, MattMur approved these changes

2022-06-17 18:07 UTC, merged